"""Constants
"""


EMOJI_ADPS = "adps"
EMOJI_AHEAL = "aheal"
EMOJI_QDPS = "qdps"
EMOJI_QHEAL = "qheal"
EMOJI_DPS = "⚔️"
EMOJI_CLOCK = "⏰"

COMP = f"""\
{EMOJI_AHEAL}: Alacrity Heal
{EMOJI_QDPS}: Quickness DPS
{EMOJI_QHEAL}: Quickness Heal
{EMOJI_ADPS}: Alacrity DPS
{EMOJI_DPS}: DPS"""

CUSTOM_REACTIONS = [EMOJI_AHEAL, EMOJI_ADPS, EMOJI_QDPS, EMOJI_QHEAL]
ROLE_REACTIONS = CUSTOM_REACTIONS + [EMOJI_DPS]
